#ifndef RTW_HEADER_fuelCycle_w_trapping_multilevel_capi_h_
#define RTW_HEADER_fuelCycle_w_trapping_multilevel_capi_h_
#include "fuelCycle_w_trapping_multilevel.h"
extern void fuelCycle_w_trapping_multilevel_InitializeDataMapInfo ( void ) ;
#endif
